CREATE TABLE IF NOT EXISTS P3_EMPRESA (
	CIF CHAR(10) NOT NULL,
	NOMBRE VARCHAR(30),
	DIR VARCHAR(30),
	CP CHAR(6),
	CCC CHAR(6),
	IDTLF CHAR(2),
	PRIMARY KEY (CIF)
);

CREATE TABLE IF NOT EXISTS P3_TRABAJADOR (
	NIF CHAR(10) NOT NULL,
	NOMBRE VARCHAR(30),
	APE1 VARCHAR(30),
	APE2 VARCHAR(30),
	IDTLF CHAR(2),
	NSS CHAR(6),
	IDCAT CHAR(6),
	IDCOT CHAR(6),
	PRIMARY KEY (NIF)
)

CREATE TABLE IF NOT EXISTS P3_TLF (
	IDTLF CHAR(2),
	PRE VARCHAR(3),
	TLF CHAR(6),
	PRIMARY KEY (IDTLF)
);

CREATE TABLE IF NOT EXISTS P3_CAT (
	IDCAT CHAR(6),
	NOMBRECAT CHAR(20),
	PRIMARY KEY (IDCAT)
);

CREATE TABLE IF NOT EXISTS P3_COT (
	IDCOT CHAR(6),
	GRUPO CHAR(20),
	PRIMARY KEY (IDCOT)
);

CREATE TABLE IF NOT EXISTS P3_CONTRATO (
	IDNUMCONTRATO CHAR(6),
	FALTA DATE,
	FBAJA DATE,
	CODCONTRATO CHAR(6),
	NIF CHAR(10).
	CIF CHAR(10),
	PRIMARY KEY (IDNUMCONTRATO)
);

CREATE TABLE IF NOT EXISTS P3_TCONTRATO (
	CODCONTRATO CHAR(6),
	NOMBRE VARCHAR(255),
	PRIMARY KEY (CODCONTRATO)
);

CREATE TABLE IF NOT EXISTS P3_CONCSALARIO (
	IDCONCSALARIO CHAR(6),
	NUMCONTRATO CHAR(6),
	CONTIPO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (IDCONCSALARIO)
);

CREATE TABLE IF NOT EXISTS P3_PERCEPCION (
	IDPERCEPCION CHAR(6),
	NUMCONTRATO CHAR(6),
	CONTIPO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (IDPERCEPCION)
);

CREATE TABLE IF NOT EXISTS P3_BASESCOT (
	IDBASECOT CHAR(6),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (IDBASECOT)
);

CREATE TABLE IF NOT EXISTS P3_BASESTIPOS (
	IDBASESTIPOS CHAR(6),
	NOMBRE CHAR(30),
	PORCENTAJE INT(2),
	PRIMARY KEY (IDBASESTIPOS)
);

CREATE TABLE IF NOT EXISTS P3_DEDUCCION (
	IDDEDUCCION CHAR(6),
	NOMBRE CHAR(30),
	PORCENTAJE INT(2),
	PRIMARY KEY (IDDEDUCCION)
);

CREATE TABLE IF NOT EXISTS P3_IRPF (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DECC (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DEDDES (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DEDFP (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DEDHEXTRA (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DEDEXTRAFM (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DEDUCCION (
	DNI CHAR(10),
	TIPODEDUCCION CHAR (2),
	ANHO CHAR(6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6)
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_TIPODEDUCCION (
	TIPODEDUCCION CHAR(10),
	NOMBRE VARCHAR (10),
	RECEPTOR VARCHAR (10),
	PRIMARY KEY (TIPODEDUCCION)
);

ALTER TABLE P3_EMPRESA 
	ADD IDTLF REFERENCES P3_TLF(IDTLF);

ALTER TABLE P3_TRABAJADOR
	ADD IDTLF REFERENCES P3_TLF(IDTLF);

ALTER TABLE P3_TRABAJADOR
	ADD IDCAT REFERENCES P3_CAT(IDCAT);

ALTER TABLE P3_TRABAJADOR
	ADD IDCOD REFERENCES P3_COT(IDCOT); 

ALTER TABLE P3_CONTRATO
	ADD IDNUMCONTRATO REFERENCES P3_TCONTRATO(CODCONTRATO);

ALTER TABLE P3_CONCSALARIO 
	ADD CONTIPO REFERENCES TCONTRATO(CODCONTRATO);