CREATE TABLE IF NOT EXISTS P3_EMPRESA (
	CIF CHAR(10) NOT NULL,
	NOMBRE VARCHAR(30),
	DIR VARCHAR(30),
	CP CHAR(6),
	CCC CHAR(6),
	TLFDid CHAR(2),
	PRIMARY KEY (CIF)
);

CREATE TABLE IF NOT EXISTS P3_TRABAJADOR (
	NIF CHAR(10) NOT NULL,
	NOMBRE VARCHAR(30),
	APE1 VARCHAR(30),
	APE2 VARCHAR(30),
	TLFID CHAR(6),
	NSS CHAR(6),
	CATID CHAR(6),
	COTID CHAR(6),
	PRIMARY KEY (COTID)
)

CREATE TABLE IF NOT EXISTS P3_TLF (
	ID CHAR(6),
	PRE VARCHAR(255),
	TLF CHAR(6),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS P3_CAT (
	ID CHAR(6),
	NOMBRECAT CHAR(20),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS P3_COT (
	ID CHAR(6),
	GRUPO CHAR(20),
	PRIMARY KEY (COT)
);

CREATE TABLE IF NOT EXISTS P3_CONTRATO (
	NUMCONTRATO CHAR(6),
	FALTA DATE,
	FBAJA DATE,
	CODCONTRATO CHAR(6),
	NIF CHAR(10).
	CIF CHAR(10),
	PRIMARY KEY (NUMCONTRATO)
);

CREATE TABLE IF NOT EXISTS P3_TCONTRATO (
	CODCONTRATO CHAR(6),
	NOMBRE VARCHAR(255),
	PRIMARY KEY (CODCONTRATO)
);

CREATE TABLE IF NOT EXISTS P3_CONCSALARIO (
	ID CHAR(6),
	NUMCONTRATO CHAR(6),
	CONTIPO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS P3_PERCEPCION (
	ID CHAR(6),
	NUMCONTRATO CHAR(6),
	CONTIPO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS P3_BASESCOT (
	ID CHAR(6),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS P3_BASESTIPOS (
	ID CHAR(6),
	NOMBRE CHAR(30),
	PORCENTAJE INT(2),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS P3_DEDUCION (
	ID CHAR(6),
	NOMBRE CHAR(30),
	PORCENTAJE INT(2),
	PRIMARY KEY (ID)
);

