
USE 21_db_JoseMaria;

CREATE TABLE IF NOT EXISTS P3_EMPRESA (
	CIF CHAR(10) NOT NULL,
	NOMBRE VARCHAR(40),
	DIR VARCHAR(40),
	CP CHAR(5),
	PROV VARCHAR(20),
	CCC BIGINT(11),
	TLF INT(9),
	PRIMARY KEY (CIF)
);

CREATE TABLE IF NOT EXISTS P3_TRABAJADOR (
	DNI CHAR(9) NOT NULL,
	NOMBRE VARCHAR(30),
	APE1 VARCHAR(30),
	APE2 VARCHAR(30),
	TLF INT(11),
	NSS BIGINT(11),
	IDCAT INT,
	IDCOT INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_TLF (
	IDTLF CHAR(2),
	PRE CHAR(3),
	TLF CHAR(6),
	PRIMARY KEY (IDTLF)
);

CREATE TABLE IF NOT EXISTS P3_CAT (
	ID INT,
	nombreCat CHAR(60),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS P3_COT (
	ID INT,
	grupo CHAR(20),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS P3_CONTRATO (
	IDNUMCONTRATO CHAR(6),
	FALTA DATE,
	FBAJA DATE,
	CODCONTRATO CHAR(6),
	NIF CHAR(10),
	CIF CHAR(10),
	PRIMARY KEY (IDNUMCONTRATO)
);

CREATE TABLE IF NOT EXISTS P3_TCONTRATO (
	CODCONTRATO INT,
	NOMBRE VARCHAR(255),
	PRIMARY KEY (CODCONTRATO)
);

CREATE TABLE IF NOT EXISTS P3_CONCSALARIO (
	numcontrato CHAR(6),
	contipo CHAR(6),
	cantidad INT,
	PRIMARY KEY (numcontato)
);

CREATE TABLE IF NOT EXISTS P3_PERCEPCION (
	IDPERCEPCION CHAR(6),
	NUMCONTRATO CHAR(6),
	CONTIPO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (IDPERCEPCION)
);

CREATE TABLE IF NOT EXISTS P3_BASESCOT (
	IDBASECOT CHAR(6),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (IDBASECOT)
);

CREATE TABLE IF NOT EXISTS P3_BASESTIPOS (
	IDBASESTIPOS CHAR(6),
	NOMBRE CHAR(30),
	PORCENTAJE INT(2),
	PRIMARY KEY (IDBASESTIPOS)
);

CREATE TABLE IF NOT EXISTS P3_DEDUCCION (
	IDDEDUCCION CHAR(6),
	NOMBRE CHAR(30),
	PORCENTAJE INT(2),
	PRIMARY KEY (IDDEDUCCION)
);

CREATE TABLE IF NOT EXISTS P3_IRPF (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DECC (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DEDDES (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DEDFP (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DEDHEXTRA (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DEDEXTRAFM (
	DNI CHAR(10),
	ANHO CHAR (6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_DEDUCCION (
	DNI CHAR(10),
	TIPODEDUCCION CHAR (2),
	ANHO CHAR(6),
	MES INT,
	NIF CHAR(10),
	NUMCONTRATO CHAR(6),
	CANTIDAD INT,
	PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS P3_TIPODEDUCCION (
	TIPODEDUCCION CHAR(10),
	NOMBRE VARCHAR (10),
	RECEPTOR VARCHAR (10),
	PRIMARY KEY (TIPODEDUCCION)
);

CREATE TABLE P3_CONCTIPO (
	conTipo INT,
	nombre CHAR(40),
	tipo CHAR(20),
	PRIMARY KEY(conTipo)
);

ALTER TABLE P3_TRABAJADOR
	ADD FOREIGN KEY (IDTLF) REFERENCES P3_TLF(IDTLF);

ALTER TABLE P3_TRABAJADOR
	ADD FOREIGN KEY (IDCAT) REFERENCES P3_CAT(ID);

ALTER TABLE P3_TRABAJADOR
	ADD FOREIGN KEY (IDCOT) REFERENCES P3_COT(IDCOT); 

ALTER TABLE P3_CONTRATO
	ADD FOREIGN KEY (IDNUMCONTRATO) REFERENCES P3_TCONTRATO(CODCONTRATO);